# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/graph_rewrite/',
                'doc_host': 'https://DeanLight.github.io',
                'git_url': 'https://github.com/DeanLight/graph_rewrite/',
                'lib_path': 'graph_rewrite'},
  'syms': { 'graph_rewrite.core': {'graph_rewrite.core.foo': ('core.html#foo', 'graph_rewrite/core.py')},
            'graph_rewrite.matcher': { 'graph_rewrite.matcher.find_struct_matches': ( 'matcher.html#find_struct_matches',
                                                                                      'graph_rewrite/matcher.py')}}}
