# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/graph_rewrite/',
                'doc_host': 'https://DeanLight.github.io',
                'git_url': 'https://github.com/DeanLight/graph_rewrite/',
                'lib_path': 'graph_rewrite'},
  'syms': { 'graph_rewrite.core': {'graph_rewrite.core.foo': ('core.html#foo', 'graph_rewrite/core.py')},
            'graph_rewrite.stub': {'graph_rewrite.stub.bar': ('stub.html#bar', 'graph_rewrite/stub.py')}}}
