# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_condition_filter.ipynb.

# %% auto 0
__all__ = ['filter_matches']

# %% ../nbs/04_condition_filter.ipynb 4
from .result_set import Match, ResultSet
from typing import *

# %% ../nbs/04_condition_filter.ipynb 6
def filter_matches(unfiltered_results: ResultSet, condition: Callable[[Match], bool]) -> ResultSet:
    return ResultSet([match for match in unfiltered_results if condition(match)])
