# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['GraphRewriteException']

# %% ../nbs/00_core.ipynb 4
class GraphRewriteException(Exception):
    def __init__(self, message="Something went wrong."):
        self.message = message
        super().__init__(self.message)
