# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_match_class.ipynb.

# %% auto 0
__all__ = ['convert_to_edge_name', 'is_anonymous_node', 'NodeAttributeAccessor', 'EdgeAttributeAccessor', 'Match',
           'mapping_to_match']

# %% ../nbs/02_match_class.ipynb 6
import networkx as nx
from networkx import DiGraph
from typing import *
from .core import _create_graph, draw, GraphRewriteException, NodeName, EdgeName

# %% ../nbs/02_match_class.ipynb 13
def convert_to_edge_name(src: NodeName, dest: NodeName) -> str:
    """Given a pair of node names, source and destination, return the name of the edge
    connecting the two in the format {src}->{dest}, which is the same format the parser
    uses to create edges in the pattern graph.

    Args:
        src (NodeName): A node name
        dest (NodeName): A node name

    Returns:
        str: A representative name for the edge (src, dest).
    """
    return f"{src}->{dest}"

# %% ../nbs/02_match_class.ipynb 15
def is_anonymous_node(node_name: NodeName) -> bool:
    """Given a name of a node in the pattern graph, return true if it begins with '$',
    which is the notion the parser uses to denote anonymous nodes.

    Args:
        node_name (NodeName): A node name in the pattern

    Returns:
        bool: Returns True if the node is anonymous, False otherwise.
    """
    return len(node_name) >= 1 and node_name[0] == '_'

# %% ../nbs/02_match_class.ipynb 16
class NodeAttributeAccessor:
    """
    This class acts as a wrapper for a set of nodes, allowing access to specific attributes.
    """
    def __init__(self, nodes):
        self.nodes = nodes

    def __getitem__(self, attribute):
        """
        Return a list of the requested attribute from each node in the set

        Args:
            attribute: The attribute to retrieve from each node

        Returns:
            List: A list of the requested attribute from each node in the set
        """
        return [getattr(node, attribute) for node in self.nodes if hasattr(node, attribute)]

class EdgeAttributeAccessor:
    """
    This class acts as a wrapper for a set of edges, allowing access to specific attributes.
    """
    def __init__(self, edges):
        self.edges = edges

    def __getitem__(self, attribute):
        """
        Return a list of the requested attribute from each edge in the set

        Args:
            attribute: The attribute to retrieve from each edge

        Returns:
            List: A list of the requested attribute from each edge in the set
        """
        return [getattr(edge, attribute) for edge in self.edges if hasattr(edge, attribute)]

# %% ../nbs/02_match_class.ipynb 19
class Match:
    """Represents a single match of a pattern inside an input graph.
     Provides a subview to a graph, limited to the nodes, edges and attributes specified in the pattern.
    """
    def __init__(self, graph: DiGraph, nodes: List[NodeName], edges: List[EdgeName], 
                 mapping: Dict[NodeName, Set[NodeName]], collection_nodes: List[NodeName]):
        self.graph: DiGraph = graph
        self._nodes: List[NodeName] = nodes
        self._edges: List[EdgeName] = edges
        self.mapping: Dict[NodeName, Set[NodeName]] = mapping # Node names and edges can represent either single nodes or collections of nodes, so for each node name is mapped to a set of input nodes:
        #TODO: Show Dean - I think it is needed to distinguish between single pattern nodes with a single match and a collection pattern node with a single match
        # If we only check if there is only one input node, we can't distinguish between a single pattern node with a single match and a collection pattern node with a single match
        self._collection_nodes: Set[NodeName] = set(collection_nodes)     
    def _check_node_in_pattern(self, pattern_node: NodeName):
        if not pattern_node in self._nodes:
            raise GraphRewriteException(f"Node {pattern_node} does not exist in the pattern")
        
    def _check_edge_in_pattern(self, pattern_src: NodeName, pattern_dst: NodeName):
        if not (pattern_src, pattern_dst) in self._edges:
            raise GraphRewriteException(f"Edge {(pattern_src, pattern_dst)} does not exist in the pattern")
    
    def _is_collection(self, pattern_node: NodeName) -> bool:
        return pattern_node in self._collection_nodes
    
    def __get_node(self, pattern_node):
        """
        Returns the node or the collection of nodes mapped to the pattern node

        Args:
            pattern_node: The node in the pattern

        Returns:
            The node or the collection of nodes mapped to the pattern node
        """
        self._check_node_in_pattern(pattern_node)
        input_nodes = self.mapping[pattern_node]

        if self._is_single(pattern_node):
            return self.graph.nodes[list(input_nodes)[0]]
        return [self.graph.nodes[input_node] for input_node in input_nodes]
    
    def __get_edge(self, pattern_src, pattern_dst):
        """
        Returns the edge or the collection of edges mapped to the pattern edge

        Args:
            pattern_src: The source node in the pattern
            pattern_dst: The destination node in the pattern

        Returns:
            The edge or the collection of edges mapped to the pattern edge
        """
        self._check_edge_in_pattern(pattern_src, pattern_dst)
        input_src_nodes = self.mapping[pattern_src]
        input_dst_nodes = self.mapping[pattern_dst]
        if self._is_collection(pattern_src) or self._is_collection(pattern_dst):
            return [self.graph.edges[input_src_node, input_dst_node] for input_src_node, input_dst_node in product(input_src_nodes, input_dst_nodes)]
        return self.graph.edges[list(input_src_nodes)[0], list(input_dst_nodes)[0]]
    
    def nodes(self):
        return {pattern_node: self.__get_node(pattern_node) for pattern_node in self._nodes}        
    
    def edges(self):
        return {convert_to_edge_name(pattern_src, pattern_dest): self.__get_edge(pattern_src, pattern_dest) for (pattern_src, pattern_dest) in self._edges}

    def set_graph(self, graph: DiGraph):
        self.graph = graph

    def __eq__(self, other):
        if type(other) is Match and len(other.mapping.items()) == len(self.mapping.items()):
            return all([other.mapping.get(k) == v for k,v in self.mapping.items()])
        return False

    def __getitem__(self, key: Union[NodeName, str]):
        """
        Returns the node/edge (single or collections) of the input graph, which was mapped by the key in the pattern during matching.
        Supports nested access when the result is a set of nodes or edges (i.e. a collection).

        Args:
            key (Union[NodeName, str]): A symbolic name used by the pattern (for a node / edge)

        Raises:
            GraphRewriteException: If the key doesn't exist in the pattern, or is mapped to a node/edge
            which does not exist anymore (due to removal by the transformation, for example).

        Returns:
            The corresponding node/edge of the input graph, or a list of 'name' attributes if requested.
            If the result is a set of nodes or edges (if it is a collection), returns a NodeAttributeAccessor or EdgeAttributeAccessor respectively, 
            to allow access to specific attributes of each node/edge in the collection.
        """
        try:
            # Check if the key is for an edge ("node1->node2")
            if str(key).__contains__("->") and len(str(key).split("->")) == 2:
                end_nodes = str(key).split("->")
                edge_or_edges = self.__get_edge(end_nodes[0], end_nodes[1])
                
                if self._is_collection(end_nodes[0]) or self._is_collection(end_nodes[1]): # If the edge is connected to a collection of nodes
                    return EdgeAttributeAccessor(edge_or_edges)
                else: # Single edge
                    return edge_or_edges
            
            # Otherwise, assume it's for a node
            node_or_nodes = self.__get_node(key)
            
            # If the result is a set of nodes, return a NodeAttributeAccessor, that creates a list of attributes for each node in the set
            if self._is_collection(key):
                return NodeAttributeAccessor(node_or_nodes)
            else: # Single node
                return node_or_nodes
        except:
            raise GraphRewriteException(f"The symbol {key} does not exist in the pattern, or it was removed from the graph")
        
    def __str__(self):
        return self.mapping.__str__()

# %% ../nbs/02_match_class.ipynb 21
def mapping_to_match(input: DiGraph, pattern: DiGraph, collections_pattern: DiGraph, mapping: Dict[NodeName, Set[NodeName]],
                      node_type_mapping: Dict[NodeName,NodeType], filter: bool=True) -> Match:
    """Given a mapping, which denotes a match of the pattern in the input graph,
    create a corresponding instance of the Match class.

    Args:
        input (DiGraph): An input graph
        pattern (DiGraph): A pattern graph
        mapping (Dict[NodeName, Set[NodeName]]): A mapping of nodes in the pattern to nodes in the input graph
        node_type_mapping (Dict[NodeName, NodeType]): A mapping of nodes in the pattern to their type (single or collection)
        filter (bool): If True, filter out anonymous nodes from the match

    Returns:
        Match: A corresponding instance of the Match class
    """
    nodes_list = []
    edges_list = []

    cleared_mapping = mapping.copy()

    for pattern_node in mapping.keys():
        if filter and is_anonymous_node(pattern_node):
            cleared_mapping.pop(pattern_node)
            continue # as we don't want to include this node in the Match
        nodes_list.append(pattern_node)

    for (n1, n2) in pattern.edges:
        if filter and (is_anonymous_node(n1) or is_anonymous_node(n2)):
            continue # as before
        edges_list.append((n1, n2))

    return Match(input, nodes_list, edges_list, cleared_mapping, node_type_mapping)
