# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_render_rhs.ipynb.

# %% auto 0
__all__ = ['RenderFunc', 'render_rhs']

# %% ../nbs/05_render_rhs.ipynb 3
RenderFunc = Callable[Match, str]

# %% ../nbs/05_render_rhs.ipynb 5
def render_rhs(result_set: ResultSet, rhs: Union[str, Template], render_func: Dict[str, RenderFunc]) -> List[str]:
    # if type(rhs) != Template:
    #   return [rhs] * length of result_set.matches, as rhs is already rendered

    # initialize rendered_rhs, an empty list
    # for match in result_set.matches:
    #   cur_calc_args = {attr: render_func[attr](match) for attr in render_func.keys}
    #   cur_rendered = rhs.render(cur_calculated_args)
    #   append cur_rendered to rendered_rhs

    # return rendered_rhs
    pass
