# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_stub.ipynb.

# %% auto 0
__all__ = ['bar']

# %% ../nbs/01_stub.ipynb 2
from .core import foo

foo()

# %% ../nbs/01_stub.ipynb 3
def bar():
    print("hey")
