# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_stub.ipynb.

# %% auto 0
__all__ = ['bar']

# %% ../nbs/01_stub.ipynb 3
from .core import foo

foo()

# %% ../nbs/01_stub.ipynb 5
def bar():
    foo()
    print("hey")
